// Complete elements data
const ELEMENTS = [
  { z:1, sym:"H", name:"Hidrogen", mass:1.008, cat:"nonmetal", group:1, period:1, block:"s",
    melt:-259.14, boil:-252.87, density:0.00008988, eneg:2.2, radius:53,
    phase:"Gas", config:"1s¹", shells:[1],
    discovered:"Henry Cavendish (1766)", desc:"Unsur paling ringan dan paling melimpah di alam semesta. Menyusun sekitar 75% dari materi biasa. Merupakan bahan bakar bintang melalui reaksi fusi nuklir.",
    uses:["Bahan Bakar","Amonia","Margarin","Roket"] },
  { z:2, sym:"He", name:"Helium", mass:4.003, cat:"noble", group:18, period:1, block:"s",
    melt:null, boil:-268.93, density:0.0001664, eneg:null, radius:31,
    phase:"Gas", config:"1s²", shells:[2],
    discovered:"Pierre Janssen (1868)", desc:"Gas mulia kedua terlighter, tidak bereaksi dengan zat lain. Ditemukan pertama kali di matahari. Digunakan untuk mendinginkan magnet superkonduktor.",
    uses:["Balon","MRI","Pengelasan","Kriogenik"] },
  { z:3, sym:"Li", name:"Litium", mass:6.941, cat:"alkali", group:1, period:2, block:"s",
    melt:180.54, boil:1347, density:0.534, eneg:0.98, radius:167,
    phase:"Padat", config:"[He] 2s¹", shells:[2,1],
    discovered:"Johan August Arfwedson (1817)", desc:"Logam alkali terlighter. Sangat reaktif dan mudah terbakar. Digunakan secara luas dalam baterai lithium-ion yang menggerakkan perangkat elektronik modern.",
    uses:["Baterai","Keramik","Kaca","Obat Bipolar"] },
  { z:4, sym:"Be", name:"Berilium", mass:9.012, cat:"alkaline", group:2, period:2, block:"s",
    melt:1287, boil:2470, density:1.85, eneg:1.57, radius:112,
    phase:"Padat", config:"[He] 2s²", shells:[2,2],
    discovered:"Louis Vauquelin (1798)", desc:"Logam alkali tanah yang sangat ringan dan kaku. Transparan terhadap sinar-X. Berbahaya jika terhirup dalam bentuk debu karena dapat menyebabkan beriliosis.",
    uses:["Aerospace","Sinar-X","Elektronik","Nuklir"] },
  { z:5, sym:"B", name:"Boron", mass:10.81, cat:"metalloid", group:13, period:2, block:"p",
    melt:2075, boil:4000, density:2.34, eneg:2.04, radius:87,
    phase:"Padat", config:"[He] 2s² 2p¹", shells:[2,3],
    discovered:"Humphry Davy (1808)", desc:"Metaloid yang ditemukan dalam bahan tambang boraks. Penting untuk pertumbuhan tanaman. Digunakan dalam produksi kaca borosilikat (Pyrex) yang tahan panas.",
    uses:["Kaca Pyrex","Pupuk","Nuklir","Keramik"] },
  { z:6, sym:"C", name:"Karbon", mass:12.011, cat:"nonmetal", group:14, period:2, block:"p",
    melt:3550, boil:4827, density:2.267, eneg:2.55, radius:77,
    phase:"Padat", config:"[He] 2s² 2p²", shells:[2,4],
    discovered:"Zaman Prasejarah", desc:"Dasar kimia organik dan kehidupan. Hadir dalam bentuk grafit, berlian, dan fullerene. Berlian adalah bahan alami terkeras, sementara grafit adalah konduktor listrik yang baik.",
    uses:["Baja","Berlian","Plastik","Bahan Bakar"] },
  { z:7, sym:"N", name:"Nitrogen", mass:14.007, cat:"nonmetal", group:15, period:2, block:"p",
    melt:-210.01, boil:-195.79, density:0.001251, eneg:3.04, radius:75,
    phase:"Gas", config:"[He] 2s² 2p³", shells:[2,5],
    discovered:"Daniel Rutherford (1772)", desc:"Menyusun 78% atmosfer bumi. Komponen utama protein dan DNA. Nitrogen cair (-196°C) digunakan untuk kriopreservasi dan pendinginan supercepat.",
    uses:["Pupuk","Amonia","Kriogenik","Spritus"] },
  { z:8, sym:"O", name:"Oksigen", mass:15.999, cat:"nonmetal", group:16, period:2, block:"p",
    melt:-218.79, boil:-182.96, density:0.001429, eneg:3.44, radius:73,
    phase:"Gas", config:"[He] 2s² 2p⁴", shells:[2,6],
    discovered:"Carl Wilhelm Scheele (1771)", desc:"Elemen ketiga terlimpah di alam semesta. Sangat penting untuk kehidupan aerobik. Membentuk ozon di stratosfer yang melindungi bumi dari radiasi UV berbahaya.",
    uses:["Pernafasan","Baja","Medis","Roket"] },
  { z:9, sym:"F", name:"Fluor", mass:18.998, cat:"halogen", group:17, period:2, block:"p",
    melt:-219.67, boil:-188.11, density:0.001696, eneg:3.98, radius:64,
    phase:"Gas", config:"[He] 2s² 2p⁵", shells:[2,7],
    discovered:"Henri Moissan (1886)", desc:"Unsur paling elektronegatif dan paling reaktif. Dapat bereaksi dengan hampir semua zat. Digunakan dalam pasta gigi sebagai fluorida untuk mencegah kerusakan gigi.",
    uses:["Pasta Gigi","Teflon","Uranium","Obat-obatan"] },
  { z:10, sym:"Ne", name:"Neon", mass:20.18, cat:"noble", group:18, period:2, block:"p",
    melt:-248.59, boil:-246.05, density:0.0008999, eneg:null, radius:38,
    phase:"Gas", config:"[He] 2s² 2p⁶", shells:[2,8],
    discovered:"William Ramsay (1898)", desc:"Gas mulia yang terkenal karena cahaya merah-oranye dalam lampu neon. Digunakan dalam tabung lucutan gas, laser, dan sebagai refrigeran kriogenik.",
    uses:["Lampu Neon","Laser","Pendingin","Periklanan"] },
  { z:11, sym:"Na", name:"Natrium", mass:22.99, cat:"alkali", group:1, period:3, block:"s",
    melt:97.72, boil:883, density:0.968, eneg:0.93, radius:190,
    phase:"Padat", config:"[Ne] 3s¹", shells:[2,8,1],
    discovered:"Humphry Davy (1807)", desc:"Logam alkali yang sangat reaktif. Bereaksi keras dengan air menghasilkan hidrogen. Natrium klorida (garam meja) adalah senyawa natrium yang paling umum dan penting bagi kehidupan.",
    uses:["Garam","Sabun","Lampu Jalan","Baterai"] },
  { z:12, sym:"Mg", name:"Magnesium", mass:24.305, cat:"alkaline", group:2, period:3, block:"s",
    melt:650, boil:1090, density:1.738, eneg:1.31, radius:145,
    phase:"Padat", config:"[Ne] 3s²", shells:[2,8,2],
    discovered:"Joseph Black (1755)", desc:"Logam ringan yang banyak digunakan dalam industri. Komponen klorofil pada tumbuhan. Terbakar dengan nyala putih yang sangat terang. Penting untuk metabolism tulang manusia.",
    uses:["Alloy","Kembang Api","Suplemen","Otomotif"] },
  { z:13, sym:"Al", name:"Aluminium", mass:26.982, cat:"post-trans", group:13, period:3, block:"p",
    melt:660.32, boil:2519, density:2.698, eneg:1.61, radius:118,
    phase:"Padat", config:"[Ne] 3s² 3p¹", shells:[2,8,3],
    discovered:"Hans Christian Ørsted (1825)", desc:"Logam paling melimpah di kerak bumi. Ringan, kuat, dan tahan korosi. Digunakan secara luas dalam transportasi, konstruksi, dan kemasan makanan.",
    uses:["Pesawat","Kemasan","Kabel","Konstruksi"] },
  { z:14, sym:"Si", name:"Silikon", mass:28.085, cat:"metalloid", group:14, period:3, block:"p",
    melt:1414, boil:3265, density:2.329, eneg:1.9, radius:111,
    phase:"Padat", config:"[Ne] 3s² 3p²", shells:[2,8,4],
    discovered:"Jöns Jacob Berzelius (1824)", desc:"Semikonduktor paling penting di dunia. Menyusun lebih dari 25% kerak bumi. Dasar dari revolusi elektronik modern. Silicon Valley dinamai dari unsur ini.",
    uses:["Chip","Solar Cell","Gelas","Semen"] },
  { z:15, sym:"P", name:"Fosfor", mass:30.974, cat:"nonmetal", group:15, period:3, block:"p",
    melt:44.15, boil:280.5, density:1.82, eneg:2.19, radius:106,
    phase:"Padat", config:"[Ne] 3s² 3p³", shells:[2,8,5],
    discovered:"Hennig Brand (1669)", desc:"Ditemukan dari urin manusia. Fosfor putih bersinar dalam gelap dan sangat beracun. Fosfor merah lebih stabil. Penting untuk DNA, ATP, dan tulang.",
    uses:["Pupuk","Korek Api","Deterjen","Pestisida"] },
  { z:16, sym:"S", name:"Sulfur", mass:32.06, cat:"nonmetal", group:16, period:3, block:"p",
    melt:115.21, boil:444.61, density:2.067, eneg:2.58, radius:102,
    phase:"Padat", config:"[Ne] 3s² 3p⁴", shells:[2,8,6],
    discovered:"Zaman Prasejarah", desc:"Dikenal sejak zaman kuno sebagai 'belerang'. Terdapat di dekat gunung berapi dan sumber panas bumi. Penting untuk produksi asam sulfat, bahan kimia industri terpenting.",
    uses:["Asam Sulfat","Karet","Bubuk Mesiu","Fungisida"] },
  { z:17, sym:"Cl", name:"Klor", mass:35.45, cat:"halogen", group:17, period:3, block:"p",
    melt:-101.5, boil:-34.04, density:0.003214, eneg:3.16, radius:99,
    phase:"Gas", config:"[Ne] 3s² 3p⁵", shells:[2,8,7],
    discovered:"Carl Wilhelm Scheele (1774)", desc:"Gas kuning-hijau beracun. Digunakan sebagai senjata kimia pada Perang Dunia I. Sekarang digunakan untuk desinfeksi air minum dan produksi PVC.",
    uses:["Disinfektan","PVC","Kertas","Obat-obatan"] },
  { z:18, sym:"Ar", name:"Argon", mass:39.948, cat:"noble", group:18, period:3, block:"p",
    melt:-189.35, boil:-185.85, density:0.001784, eneg:null, radius:71,
    phase:"Gas", config:"[Ne] 3s² 3p⁶", shells:[2,8,8],
    discovered:"Lord Rayleigh & William Ramsay (1894)", desc:"Gas mulia ketiga terlimpah di atmosfer bumi (0.93%). Tidak reaktif sehingga digunakan sebagai gas pelindung dalam pengelasan dan produksi logam.",
    uses:["Pengelasan","Lampu Pijar","Semikonduktor","Neon Sign"] },
  { z:19, sym:"K", name:"Kalium", mass:39.098, cat:"alkali", group:1, period:4, block:"s",
    melt:63.38, boil:759, density:0.862, eneg:0.82, radius:243,
    phase:"Padat", config:"[Ar] 4s¹", shells:[2,8,8,1],
    discovered:"Humphry Davy (1807)", desc:"Logam alkali yang penting untuk fungsi sel tubuh. Ion kalium mengatur keseimbangan cairan dan transmisi sinyal saraf. Sangat melimpah dalam buah pisang.",
    uses:["Pupuk","Sabun","Kaca","Suplemen Gizi"] },
  { z:20, sym:"Ca", name:"Kalsium", mass:40.078, cat:"alkaline", group:2, period:4, block:"s",
    melt:842, boil:1484, density:1.55, eneg:1.0, radius:194,
    phase:"Padat", config:"[Ar] 4s²", shells:[2,8,8,2],
    discovered:"Humphry Davy (1808)", desc:"Unsur kelima terlimpah di kerak bumi dan dalam tubuh manusia. Komponen utama tulang dan gigi. Berperan penting dalam kontraksi otot dan pembekuan darah.",
    uses:["Semen","Baja","Suplemen","Kapur"] },
  { z:21, sym:"Sc", name:"Skandium", mass:44.956, cat:"transition", group:3, period:4, block:"d",
    melt:1541, boil:2836, density:2.985, eneg:1.36, radius:184,
    phase:"Padat", config:"[Ar] 3d¹ 4s²", shells:[2,8,9,2],
    discovered:"Lars Fredrik Nilson (1879)", desc:"Logam transisi langka yang ringan. Digunakan dalam lampu intensitas tinggi dan paduan aluminium untuk peralatan olahraga dan aerospace.",
    uses:["Alloy","Lampu","Aerospace","Bahan Bakar"] },
  { z:22, sym:"Ti", name:"Titanium", mass:47.867, cat:"transition", group:4, period:4, block:"d",
    melt:1668, boil:3287, density:4.506, eneg:1.54, radius:176,
    phase:"Padat", config:"[Ar] 3d² 4s²", shells:[2,8,10,2],
    discovered:"William Gregor (1791)", desc:"Logam kuat, ringan, dan tahan korosi. Kekuatan setara baja tapi 45% lebih ringan. Biokompatibel sehingga digunakan dalam implan medis dan prostetik gigi.",
    uses:["Pesawat","Implan Medis","Pigmen","Armor"] },
  { z:23, sym:"V", name:"Vanadium", mass:50.942, cat:"transition", group:5, period:4, block:"d",
    melt:1910, boil:3407, density:6.0, eneg:1.63, radius:171,
    phase:"Padat", config:"[Ar] 3d³ 4s²", shells:[2,8,11,2],
    discovered:"Andrés Manuel del Río (1801)", desc:"Logam transisi yang digunakan untuk memperkuat baja. Vanadium pentoksida merupakan katalis penting. Ditemukan dalam darah hewan laut tertentu.",
    uses:["Baja Kuat","Katalis","Baterai","Titanium Alloy"] },
  { z:24, sym:"Cr", name:"Kromium", mass:51.996, cat:"transition", group:6, period:4, block:"d",
    melt:1907, boil:2671, density:7.15, eneg:1.66, radius:166,
    phase:"Padat", config:"[Ar] 3d⁵ 4s¹", shells:[2,8,13,1],
    discovered:"Louis Nicolas Vauquelin (1797)", desc:"Logam yang memberikan kilau chrome pada baja dan otomotif. Baja tahan karat mengandung minimal 10.5% chromium. Kata 'chrome' berasal dari bahasa Yunani 'warna'.",
    uses:["Baja Stainless","Elektroplating","Pigmen","Tanning Kulit"] },
  { z:25, sym:"Mn", name:"Mangan", mass:54.938, cat:"transition", group:7, period:4, block:"d",
    melt:1246, boil:2061, density:7.21, eneg:1.55, radius:161,
    phase:"Padat", config:"[Ar] 3d⁵ 4s²", shells:[2,8,13,2],
    discovered:"Johan Gottlieb Gahn (1774)", desc:"Digunakan terutama dalam produksi baja. Penambahan mangan meningkatkan kekerasan dan ketahanan baja. Juga digunakan dalam baterai alkalin dan produksi kaca.",
    uses:["Baja","Baterai","Pupuk","Kaca"] },
  { z:26, sym:"Fe", name:"Besi", mass:55.845, cat:"transition", group:8, period:4, block:"d",
    melt:1538, boil:2861, density:7.874, eneg:1.83, radius:156,
    phase:"Padat", config:"[Ar] 3d⁶ 4s²", shells:[2,8,14,2],
    discovered:"Zaman Prasejarah", desc:"Logam paling banyak digunakan manusia sepanjang sejarah. Komponen utama baja. Inti bumi sebagian besar terdiri dari besi. Penting untuk hemoglobin dalam darah.",
    uses:["Baja","Konstruksi","Otomotif","Hemoglobin"] },
  { z:27, sym:"Co", name:"Kobalt", mass:58.933, cat:"transition", group:9, period:4, block:"d",
    melt:1495, boil:2927, density:8.9, eneg:1.88, radius:152,
    phase:"Padat", config:"[Ar] 3d⁷ 4s²", shells:[2,8,15,2],
    discovered:"Georg Brandt (1732)", desc:"Logam berwarna biru-perak. Kobalt-60 digunakan dalam terapi kanker radiasi. Komponen vitamin B12 yang penting untuk fungsi saraf. Digunakan dalam pigmen biru.",
    uses:["Baterai Li-ion","Superalloy","Pigmen Biru","Magnet"] },
  { z:28, sym:"Ni", name:"Nikel", mass:58.693, cat:"transition", group:10, period:4, block:"d",
    melt:1455, boil:2913, density:8.908, eneg:1.91, radius:149,
    phase:"Padat", config:"[Ar] 3d⁸ 4s²", shells:[2,8,16,2],
    discovered:"Axel Fredrik Cronstedt (1751)", desc:"Logam tahan korosi yang digunakan dalam uang koin, baterai, dan peralatan dapur tahan karat. Meteorit biasanya mengandung paduan besi-nikel.",
    uses:["Stainless Steel","Baterai","Koin","Elektroplating"] },
  { z:29, sym:"Cu", name:"Tembaga", mass:63.546, cat:"transition", group:11, period:4, block:"d",
    melt:1084.62, boil:2562, density:8.96, eneg:1.9, radius:145,
    phase:"Padat", config:"[Ar] 3d¹⁰ 4s¹", shells:[2,8,18,1],
    discovered:"Zaman Prasejarah (~9000 SM)", desc:"Salah satu logam pertama yang digunakan manusia. Konduktor listrik dan panas terbaik setelah perak. Patina hijau (verdigris) yang terbentuk secara alami melindungi tembaga dari korosi.",
    uses:["Kabel Listrik","Pipa","Koin","Perunggu"] },
  { z:30, sym:"Zn", name:"Seng", mass:65.38, cat:"transition", group:12, period:4, block:"d",
    melt:419.53, boil:907, density:7.133, eneg:1.65, radius:142,
    phase:"Padat", config:"[Ar] 3d¹⁰ 4s²", shells:[2,8,18,2],
    discovered:"India/China (~1000 SM)", desc:"Logam yang penting untuk sistem kekebalan tubuh manusia. Digunakan untuk galvanisasi baja agar tahan karat. Kuningan adalah paduan seng dan tembaga.",
    uses:["Galvanisasi","Kuningan","Suplemen","Baterai"] },
  { z:31, sym:"Ga", name:"Galium", mass:69.723, cat:"post-trans", group:13, period:4, block:"p",
    melt:29.76, boil:2204, density:5.91, eneg:1.81, radius:136,
    phase:"Padat", config:"[Ar] 3d¹⁰ 4s² 4p¹", shells:[2,8,18,3],
    discovered:"Lecoq de Boisbaudran (1875)", desc:"Logam dengan titik leleh sangat rendah (meleleh di tangan). Digunakan dalam semikonduktor gallium arsenide (GaAs) untuk LED dan sel surya efisiensi tinggi.",
    uses:["LED","Semikonduktor","Termometer","Cermin"] },
  { z:32, sym:"Ge", name:"Germanium", mass:72.63, cat:"metalloid", group:14, period:4, block:"p",
    melt:938.25, boil:2833, density:5.323, eneg:2.01, radius:125,
    phase:"Padat", config:"[Ar] 3d¹⁰ 4s² 4p²", shells:[2,8,18,4],
    discovered:"Clemens Winkler (1886)", desc:"Metaloid semikonduktor yang diprediksi keberadaannya oleh Mendeleev. Transparan terhadap inframerah sehingga digunakan dalam optik inframerah dan fiber optik.",
    uses:["Semikonduktor","Fiber Optik","Inframerah","Katalis"] },
  { z:33, sym:"As", name:"Arsen", mass:74.922, cat:"metalloid", group:15, period:4, block:"p",
    melt:817, boil:614, density:5.727, eneg:2.18, radius:114,
    phase:"Padat", config:"[Ar] 3d¹⁰ 4s² 4p³", shells:[2,8,18,5],
    discovered:"Albertus Magnus (~1250)", desc:"Metaloid beracun yang terkenal sebagai racun sepanjang sejarah. Digunakan dalam semikonduktor GaAs. Dalam jumlah kecil ditemukan secara alami dalam tanah dan air.",
    uses:["Semikonduktor","Pestisida","Pengawet Kayu","Kaca"] },
  { z:34, sym:"Se", name:"Selenium", mass:78.971, cat:"nonmetal", group:16, period:4, block:"p",
    melt:221, boil:685, density:4.809, eneg:2.55, radius:103,
    phase:"Padat", config:"[Ar] 3d¹⁰ 4s² 4p⁴", shells:[2,8,18,6],
    discovered:"Jöns Jacob Berzelius (1817)", desc:"Sifat konduktivitas listriknya meningkat saat terkena cahaya (fotokonduktif). Digunakan dalam sel solar, fotokopi, dan sebagai mineral esensial dalam nutrisi hewan.",
    uses:["Fotokopi","Solar Cell","Kaca","Suplemen"] },
  { z:35, sym:"Br", name:"Bromin", mass:79.904, cat:"halogen", group:17, period:4, block:"p",
    melt:-7.2, boil:58.8, density:3.122, eneg:2.96, radius:94,
    phase:"Cair", config:"[Ar] 3d¹⁰ 4s² 4p⁵", shells:[2,8,18,7],
    discovered:"Antoine Balard (1826)", desc:"Salah satu dari dua unsur yang berwujud cair pada suhu kamar. Cairan merah-cokelat dengan uap beracun. Nama berasal dari bahasa Yunani 'bromos' (bau busuk).",
    uses:["Pestisida","Obat-obatan","Pewarna","Penghambat Api"] },
  { z:36, sym:"Kr", name:"Kripton", mass:83.798, cat:"noble", group:18, period:4, block:"p",
    melt:-157.36, boil:-153.22, density:0.003733, eneg:null, radius:88,
    phase:"Gas", config:"[Ar] 3d¹⁰ 4s² 4p⁶", shells:[2,8,18,8],
    discovered:"William Ramsay (1898)", desc:"Gas mulia yang namanya berasal dari bahasa Yunani 'kryptos' (tersembunyi). Kripton-86 pernah digunakan sebagai definisi meter internasional. Digunakan dalam lampu kilat fotografi.",
    uses:["Lampu Kilat","Laser","Neon Sign","Standar Panjang"] },
  { z:37, sym:"Rb", name:"Rubidium", mass:85.468, cat:"alkali", group:1, period:5, block:"s",
    melt:39.31, boil:688, density:1.532, eneg:0.82, radius:265,
    phase:"Padat", config:"[Kr] 5s¹", shells:[2,8,18,8,1],
    discovered:"Robert Bunsen (1861)", desc:"Logam alkali yang sangat reaktif. Digunakan dalam jam atom rubidium yang sangat presisi. Terbakar dengan nyala ungu-merah indah.",
    uses:["Jam Atom","Sel Surya","Fireworks","Penelitian"] },
  { z:38, sym:"Sr", name:"Stronsium", mass:87.62, cat:"alkaline", group:2, period:5, block:"s",
    melt:777, boil:1382, density:2.64, eneg:0.95, radius:219,
    phase:"Padat", config:"[Kr] 5s²", shells:[2,8,18,8,2],
    discovered:"Adair Crawford (1790)", desc:"Logam alkali tanah yang memberikan warna merah cerah pada kembang api. Stronsium-90 adalah produk fisi radioaktif yang berbahaya dalam fallout nuklir.",
    uses:["Kembang Api","Magnet","Nuklir","Pigmen"] },
  { z:39, sym:"Y", name:"Itrium", mass:88.906, cat:"transition", group:3, period:5, block:"d",
    melt:1522, boil:3345, density:4.469, eneg:1.22, radius:212,
    phase:"Padat", config:"[Kr] 4d¹ 5s²", shells:[2,8,18,9,2],
    discovered:"Johan Gadolin (1794)", desc:"Logam transisi yang digunakan dalam superkonduktor suhu tinggi YBa₂Cu₃O₇. Digunakan dalam laser YAG untuk operasi mata dan pemotongan logam.",
    uses:["Laser","Superkonduktor","Layar TV","Magnet"] },
  { z:40, sym:"Zr", name:"Zirkonium", mass:91.224, cat:"transition", group:4, period:5, block:"d",
    melt:1855, boil:4409, density:6.52, eneg:1.33, radius:206,
    phase:"Padat", config:"[Kr] 4d² 5s²", shells:[2,8,18,10,2],
    discovered:"Martin Heinrich Klaproth (1789)", desc:"Logam tahan korosi yang digunakan dalam bahan bakar nuklir dan reaktor nuklir. Zirkonia (ZrO₂) merupakan berlian sintetis populer sebagai pengganti berlian asli.",
    uses:["Reaktor Nuklir","Zirkonia","Keramik","Aerospace"] },
  { z:41, sym:"Nb", name:"Niobium", mass:92.906, cat:"transition", group:5, period:5, block:"d",
    melt:2477, boil:4744, density:8.57, eneg:1.6, radius:198,
    phase:"Padat", config:"[Kr] 4d⁴ 5s¹", shells:[2,8,18,12,1],
    discovered:"Charles Hatchett (1801)", desc:"Logam superkonduktor pada suhu kriogenik. Digunakan dalam superkonduktor untuk MRI dan akselerator partikel. Menambah kekuatan pada baja berkekuatan tinggi.",
    uses:["Superkonduktor","Baja HSLA","MRI","Jet Engine"] },
  { z:42, sym:"Mo", name:"Molibdenum", mass:95.95, cat:"transition", group:6, period:5, block:"d",
    melt:2623, boil:4639, density:10.22, eneg:2.16, radius:190,
    phase:"Padat", config:"[Kr] 4d⁵ 5s¹", shells:[2,8,18,13,1],
    discovered:"Carl Wilhelm Scheele (1778)", desc:"Logam dengan titik leleh sangat tinggi. Komponen enzim yang memfiksasi nitrogen di alam. Digunakan dalam baja tahan panas untuk aplikasi suhu tinggi.",
    uses:["Baja Spesial","Katalis","Pelumas","Pigmen"] },
  { z:43, sym:"Tc", name:"Teknesium", mass:98, cat:"transition", group:7, period:5, block:"d",
    melt:2157, boil:4265, density:11.5, eneg:1.9, radius:183,
    phase:"Padat", config:"[Kr] 4d⁵ 5s²", shells:[2,8,18,13,2],
    discovered:"Carlo Perrier (1937)", desc:"Unsur pertama yang dibuat secara buatan. Tidak ada isotop stabil. Teknesium-99m digunakan secara luas dalam diagnostik medis nuklir (pencitraan tulang, dll).",
    uses:["Diagnostik Medis","Penelitian","Pelacak Radioaktif"] },
  { z:44, sym:"Ru", name:"Rutenium", mass:101.07, cat:"transition", group:8, period:5, block:"d",
    melt:2334, boil:4150, density:12.37, eneg:2.2, radius:178,
    phase:"Padat", config:"[Kr] 4d⁷ 5s¹", shells:[2,8,18,15,1],
    discovered:"Karl Ernst Claus (1844)", desc:"Logam platina yang keras dan langka. Digunakan sebagai katalis dan untuk mengeraskan platinum dan paladium. Digunakan dalam pena stylus dan kontak listrik.",
    uses:["Katalis","Elektroda","Pena Stylus","Solar Cell"] },
  { z:45, sym:"Rh", name:"Rodium", mass:102.91, cat:"transition", group:9, period:5, block:"d",
    melt:1964, boil:3695, density:12.41, eneg:2.28, radius:173,
    phase:"Padat", config:"[Kr] 4d⁸ 5s¹", shells:[2,8,18,16,1],
    discovered:"William Hyde Wollaston (1803)", desc:"Logam sangat langka dan mahal. Komponen penting katalis konverter pada kendaraan. Digunakan untuk pelapisan perhiasan dan cermin teleskop.",
    uses:["Katalis Konverter","Perhiasan","Cermin","Industri Kimia"] },
  { z:46, sym:"Pd", name:"Paladium", mass:106.42, cat:"transition", group:10, period:5, block:"d",
    melt:1554.9, boil:2963, density:12.02, eneg:2.2, radius:169,
    phase:"Padat", config:"[Kr] 4d¹⁰", shells:[2,8,18,18],
    discovered:"William Hyde Wollaston (1803)", desc:"Logam platina yang dapat menyerap hidrogen dalam jumlah besar. Digunakan dalam katalis konverter, peralatan gigi, dan produksi hidrogen bersih.",
    uses:["Katalis Konverter","Elektronik","Perhiasan","Hidrogen"] },
  { z:47, sym:"Ag", name:"Perak", mass:107.87, cat:"transition", group:11, period:5, block:"d",
    melt:961.78, boil:2162, density:10.49, eneg:1.93, radius:165,
    phase:"Padat", config:"[Kr] 4d¹⁰ 5s¹", shells:[2,8,18,18,1],
    discovered:"Zaman Prasejarah", desc:"Konduktor listrik dan panas terbaik di antara semua unsur. Memiliki sifat antimikroba alami. Digunakan dalam fotografi analog, perhiasan, cermin, dan kontak listrik.",
    uses:["Perhiasan","Fotografi","Elektronik","Antibakteri"] },
  { z:48, sym:"Cd", name:"Kadmium", mass:112.41, cat:"transition", group:12, period:5, block:"d",
    melt:321.07, boil:767, density:8.65, eneg:1.69, radius:161,
    phase:"Padat", config:"[Kr] 4d¹⁰ 5s²", shells:[2,8,18,18,2],
    discovered:"Friedrich Strohmeyer (1817)", desc:"Logam beracun yang menumpuk dalam ginjal. Digunakan dalam baterai nikel-kadmium. Kadmium sulfida memberikan warna kuning cerah pada cat.",
    uses:["Baterai Ni-Cd","Pigmen","Nuklir","Elektroplating"] },
  { z:49, sym:"In", name:"Indium", mass:114.82, cat:"post-trans", group:13, period:5, block:"p",
    melt:156.6, boil:2072, density:7.31, eneg:1.78, radius:156,
    phase:"Padat", config:"[Kr] 4d¹⁰ 5s² 5p¹", shells:[2,8,18,18,3],
    discovered:"Ferdinand Reich (1863)", desc:"Logam lunak yang menghasilkan bunyi 'menangis' saat ditekuk. Indium tin oxide (ITO) adalah material transparan konduktif untuk layar sentuh dan LCD.",
    uses:["Layar LCD","Layar Sentuh","Solar Cell","Solder"] },
  { z:50, sym:"Sn", name:"Timah", mass:118.71, cat:"post-trans", group:14, period:5, block:"p",
    melt:231.93, boil:2602, density:7.287, eneg:1.96, radius:145,
    phase:"Padat", config:"[Kr] 4d¹⁰ 5s² 5p²", shells:[2,8,18,18,4],
    discovered:"Zaman Prasejarah (~3500 SM)", desc:"Digunakan sejak Zaman Perunggu. 'Tin whiskers' adalah pertumbuhan kristal yang menyebabkan korsleting listrik. Solder tradisional adalah campuran timah dan timbal.",
    uses:["Solder","Kemasan Kaleng","Perunggu","Gelas"] },
  { z:51, sym:"Sb", name:"Antimon", mass:121.76, cat:"metalloid", group:15, period:5, block:"p",
    melt:630.63, boil:1587, density:6.685, eneg:2.05, radius:133,
    phase:"Padat", config:"[Kr] 4d¹⁰ 5s² 5p³", shells:[2,8,18,18,5],
    discovered:"Zaman Prasejarah", desc:"Metaloid yang digunakan sejak ribuan tahun untuk kosmetik mata (kohl). Digunakan sebagai penghambat api dan dalam baterai timbal-asam sebagai penguat.",
    uses:["Penghambat Api","Baterai","Semikonduktor","Kosmetik"] },
  { z:52, sym:"Te", name:"Telurium", mass:127.6, cat:"metalloid", group:16, period:5, block:"p",
    melt:449.51, boil:988, density:6.24, eneg:2.1, radius:123,
    phase:"Padat", config:"[Kr] 4d¹⁰ 5s² 5p⁴", shells:[2,8,18,18,6],
    discovered:"Franz-Joseph Müller (1782)", desc:"Metaloid langka yang digunakan dalam paduan logam dan semikonduktor. Digunakan dalam sel surya CdTe (Cadmium Telluride) yang efisien. Memiliki bau bawang putih yang menyengat.",
    uses:["Solar Cell CdTe","Paduan Logam","Semikonduktor","Pendingin"] },
  { z:53, sym:"I", name:"Iodin", mass:126.9, cat:"halogen", group:17, period:5, block:"p",
    melt:113.7, boil:184.3, density:4.933, eneg:2.66, radius:115,
    phase:"Padat", config:"[Kr] 4d¹⁰ 5s² 5p⁵", shells:[2,8,18,18,7],
    discovered:"Bernard Courtois (1811)", desc:"Halogen yang penting untuk fungsi tiroid. Yodium meja ditambahkan ke garam untuk mencegah penyakit gondok. Larutan yodium (betadine) digunakan sebagai antiseptik.",
    uses:["Antiseptik","Nutrisi Tiroid","Fotografi","Kimia Nuklir"] },
  { z:54, sym:"Xe", name:"Xenon", mass:131.29, cat:"noble", group:18, period:5, block:"p",
    melt:-111.75, boil:-108.12, density:0.005887, eneg:null, radius:108,
    phase:"Gas", config:"[Kr] 4d¹⁰ 5s² 5p⁶", shells:[2,8,18,18,8],
    discovered:"William Ramsay (1898)", desc:"Gas mulia yang digunakan dalam lampu xenon untuk headlight mobil dan proyektor film. Xenon dapat membentuk senyawa kimia meskipun gas mulia. Digunakan sebagai anestesi.",
    uses:["Lampu Xenon","Laser","Anestesi","Propulsi Ion"] },
  { z:55, sym:"Cs", name:"Cesium", mass:132.91, cat:"alkali", group:1, period:6, block:"s",
    melt:28.44, boil:671, density:1.873, eneg:0.79, radius:298,
    phase:"Padat", config:"[Xe] 6s¹", shells:[2,8,18,18,8,1],
    discovered:"Robert Bunsen (1860)", desc:"Logam dengan elektronegatifitas paling rendah. Cesium-133 mendefinisikan detik SI (9,192,631,770 osilasi). Jam atom cesium akurat hingga 1 detik per 300 juta tahun.",
    uses:["Jam Atom","Bor Minyak","Sel Surya","GPS"] },
  { z:56, sym:"Ba", name:"Barium", mass:137.33, cat:"alkaline", group:2, period:6, block:"s",
    melt:727, boil:1870, density:3.594, eneg:0.89, radius:253,
    phase:"Padat", config:"[Xe] 6s²", shells:[2,8,18,18,8,2],
    discovered:"Carl Wilhelm Scheele (1774)", desc:"Logam alkali tanah reaktif. Barium sulfat digunakan sebagai kontras media dalam pencitraan saluran pencernaan (barium meal). Memberikan warna hijau dalam kembang api.",
    uses:["Kontras X-Ray","Kembang Api","Bor Minyak","Kaca"] },
  // Lanthanides
  { z:57, sym:"La", name:"Lantanum", mass:138.91, cat:"lanthanide", group:3, period:6, block:"f",
    melt:920, boil:3464, density:6.162, eneg:1.1, radius:250,
    phase:"Padat", config:"[Xe] 5d¹ 6s²", shells:[2,8,18,18,9,2],
    discovered:"Carl Gustaf Mosander (1839)", desc:"Logam tanah jarang pertama dalam seri lantanida. Digunakan dalam elektroda baterai hibrida, kamera, dan teleskop. Oksida lantanum digunakan dalam kaca optik.",
    uses:["Baterai Hibrida","Optik","Catalyst","Layar"] },
  { z:58, sym:"Ce", name:"Cerium", mass:140.12, cat:"lanthanide", group:3, period:6, block:"f",
    melt:795, boil:3443, density:6.77, eneg:1.12, radius:185,
    phase:"Padat", config:"[Xe] 4f¹ 5d¹ 6s²", shells:[2,8,18,19,9,2],
    discovered:"Wilhelm Hisinger (1803)", desc:"Logam tanah jarang paling melimpah. Cerium oksida digunakan sebagai katalis dalam konverter katalitik dan poles kaca. Ferro cerium digunakan dalam batu api korek api.",
    uses:["Konverter Katalitik","Poles Kaca","Batu Api","Pigmen"] },
  { z:59, sym:"Pr", name:"Praseodimium", mass:140.91, cat:"lanthanide", group:3, period:6, block:"f",
    melt:931, boil:3520, density:6.773, eneg:1.13, radius:247,
    phase:"Padat", config:"[Xe] 4f³ 6s²", shells:[2,8,18,21,8,2],
    discovered:"Carl Auer von Welsbach (1885)", desc:"Logam tanah jarang berwarna kuning-hijau. Digunakan dalam magnet neodimium (bersama neodimium dan boron). Kaca praseodimium menyaring cahaya kuning dari nyala api las.",
    uses:["Magnet Kuat","Kaca Las","Paduan Logam","Laser"] },
  { z:60, sym:"Nd", name:"Neodimium", mass:144.24, cat:"lanthanide", group:3, period:6, block:"f",
    melt:1016, boil:3074, density:7.007, eneg:1.14, radius:206,
    phase:"Padat", config:"[Xe] 4f⁴ 6s²", shells:[2,8,18,22,8,2],
    discovered:"Carl Auer von Welsbach (1885)", desc:"Komponen utama magnet permanen terkuat (Nd₂Fe₁₄B). Magnet neodimium digunakan dalam hard disk, speaker, motor listrik EV, dan turbin angin.",
    uses:["Magnet Terkuat","Motor EV","Wind Turbine","Laser"] },
  { z:61, sym:"Pm", name:"Prometium", mass:145, cat:"lanthanide", group:3, period:6, block:"f",
    melt:1042, boil:3000, density:7.26, eneg:1.13, radius:205,
    phase:"Padat", config:"[Xe] 4f⁵ 6s²", shells:[2,8,18,23,8,2],
    discovered:"Jacob Marinsky (1945)", desc:"Satu-satunya lantanida yang tidak memiliki isotop stabil. Ditemukan sebagai produk fisi uranium. Digunakan dalam generator nuklir mini untuk satelit dan alat pacu jantung lama.",
    uses:["Generator Nuklir","Penelitian","Cat Fosfor","Pengukur Ketebalan"] },
  { z:62, sym:"Sm", name:"Samarium", mass:150.36, cat:"lanthanide", group:3, period:6, block:"f",
    melt:1072, boil:1794, density:7.52, eneg:1.17, radius:238,
    phase:"Padat", config:"[Xe] 4f⁶ 6s²", shells:[2,8,18,24,8,2],
    discovered:"Lecoq de Boisbaudran (1879)", desc:"Digunakan dalam magnet samarium-kobalt yang tahan suhu tinggi. Digunakan dalam obat kanker dan dalam reaktor nuklir sebagai penyerap neutron.",
    uses:["Magnet SmCo","Terapi Kanker","Reaktor Nuklir","Laser"] },
  { z:63, sym:"Eu", name:"Europium", mass:151.96, cat:"lanthanide", group:3, period:6, block:"f",
    melt:826, boil:1529, density:5.264, eneg:1.2, radius:231,
    phase:"Padat", config:"[Xe] 4f⁷ 6s²", shells:[2,8,18,25,8,2],
    discovered:"Eugène-Anatole Demarçay (1901)", desc:"Digunakan dalam fosfor merah dan biru pada layar TV dan lampu fluoresen. Ditemukan pada uang Euro sebagai penanda keamanan anti-pemalsuan.",
    uses:["Layar TV","Uang Euro","Lampu Fluoresen","Laser"] },
  { z:64, sym:"Gd", name:"Gadolinium", mass:157.25, cat:"lanthanide", group:3, period:6, block:"f",
    melt:1312, boil:3273, density:7.9, eneg:1.2, radius:233,
    phase:"Padat", config:"[Xe] 4f⁷ 5d¹ 6s²", shells:[2,8,18,25,9,2],
    discovered:"Jean Charles de Marignac (1880)", desc:"Digunakan sebagai zat kontras dalam MRI karena sifat paramagnetiknya yang kuat. Juga digunakan dalam reaktor nuklir sebagai penyerap neutron darurat.",
    uses:["Kontras MRI","Reaktor Nuklir","Magnet","Sensor"] },
  { z:65, sym:"Tb", name:"Terbium", mass:158.93, cat:"lanthanide", group:3, period:6, block:"f",
    melt:1356, boil:3230, density:8.23, eneg:1.2, radius:225,
    phase:"Padat", config:"[Xe] 4f⁹ 6s²", shells:[2,8,18,27,8,2],
    discovered:"Carl Gustaf Mosander (1843)", desc:"Digunakan dalam fosfor hijau cerah untuk layar. Paduan terfenol-D (terbium-besi) digunakan dalam sensor dan aktuator magnetostriktif untuk sonar.",
    uses:["Layar","Sonar","Magnet","Laser"] },
  { z:66, sym:"Dy", name:"Disprosium", mass:162.5, cat:"lanthanide", group:3, period:6, block:"f",
    melt:1407, boil:2562, density:8.55, eneg:1.22, radius:228,
    phase:"Padat", config:"[Xe] 4f¹⁰ 6s²", shells:[2,8,18,28,8,2],
    discovered:"Lecoq de Boisbaudran (1886)", desc:"Komponen penting magnet neodimium untuk meningkatkan kinerja suhu tinggi. Digunakan dalam reaktor nuklir dan batang kontrol reaktor.",
    uses:["Magnet EV","Reaktor Nuklir","Laser","Data Storage"] },
  { z:67, sym:"Ho", name:"Holmium", mass:164.93, cat:"lanthanide", group:3, period:6, block:"f",
    melt:1461, boil:2720, density:8.795, eneg:1.23, radius:226,
    phase:"Padat", config:"[Xe] 4f¹¹ 6s²", shells:[2,8,18,29,8,2],
    discovered:"Marc Delafontaine (1878)", desc:"Memiliki momen magnetik terbesar dari semua unsur alami. Digunakan dalam laser medis untuk prosedur urologi dan batu ginjal. Juga dalam reaktor nuklir.",
    uses:["Laser Medis","Magnet Kutub","Reaktor Nuklir","Penelitian"] },
  { z:68, sym:"Er", name:"Erbium", mass:167.26, cat:"lanthanide", group:3, period:6, block:"f",
    melt:1529, boil:2868, density:9.066, eneg:1.24, radius:226,
    phase:"Padat", config:"[Xe] 4f¹² 6s²", shells:[2,8,18,30,8,2],
    discovered:"Carl Gustaf Mosander (1843)", desc:"Digunakan dalam penguat fiber optik (erbium-doped fiber amplifier/EDFA) yang memungkinkan transmisi data internet jarak jauh. Erbium menambah warna merah muda pada kaca.",
    uses:["Fiber Optik","Laser","Kaca Mewah","Metalurgi"] },
  { z:69, sym:"Tm", name:"Tulium", mass:168.93, cat:"lanthanide", group:3, period:6, block:"f",
    melt:1545, boil:1950, density:9.321, eneg:1.25, radius:222,
    phase:"Padat", config:"[Xe] 4f¹³ 6s²", shells:[2,8,18,31,8,2],
    discovered:"Per Teodor Cleve (1879)", desc:"Lantanida terlangka kedua setelah prometium. Digunakan dalam laser dan sumber sinar-X portabel untuk membantu dokter di lapangan. Memancarkan cahaya biru saat dieksitasi.",
    uses:["Laser","Sumber X-Ray Portabel","Penelitian","Kaca Khusus"] },
  { z:70, sym:"Yb", name:"Iterbium", mass:173.04, cat:"lanthanide", group:3, period:6, block:"f",
    melt:824, boil:1196, density:6.965, eneg:1.1, radius:222,
    phase:"Padat", config:"[Xe] 4f¹⁴ 6s²", shells:[2,8,18,32,8,2],
    discovered:"Jean Charles de Marignac (1878)", desc:"Digunakan dalam jam optik paling akurat yang pernah dibuat. Laser ytterbium digunakan dalam manufaktur presisi dan komunikasi. Meningkatkan sifat mekanik baja tahan karat.",
    uses:["Jam Atom Presisi","Laser","Baja","Serat Optik"] },
  { z:71, sym:"Lu", name:"Lutetium", mass:174.97, cat:"lanthanide", group:3, period:6, block:"f",
    melt:1663, boil:3402, density:9.84, eneg:1.27, radius:217,
    phase:"Padat", config:"[Xe] 4f¹⁴ 5d¹ 6s²", shells:[2,8,18,32,9,2],
    discovered:"Georges Urbain (1907)", desc:"Lantanida terberat dan terpadat. Digunakan dalam detektor PET scan (lutetium oxyorthosilicate/LSO). Digunakan dalam proses katalis minyak bumi.",
    uses:["PET Scan","Refining Minyak","Laser","Penelitian"] },
  { z:72, sym:"Hf", name:"Hafnium", mass:178.49, cat:"transition", group:4, period:6, block:"d",
    melt:2233, boil:4603, density:13.31, eneg:1.3, radius:208,
    phase:"Padat", config:"[Xe] 4f¹⁴ 5d² 6s²", shells:[2,8,18,32,10,2],
    discovered:"Dirk Coster (1923)", desc:"Menyerap neutron dengan sangat efektif, digunakan dalam batang kontrol reaktor nuklir. Hafnium oxide digunakan dalam chip Intel generasi terbaru sebagai gate dielectric.",
    uses:["Reaktor Nuklir","Chip Prosesor","Superalloy","Plasma Cutting"] },
  { z:73, sym:"Ta", name:"Tantalum", mass:180.95, cat:"transition", group:5, period:6, block:"d",
    melt:3017, boil:5458, density:16.65, eneg:1.5, radius:200,
    phase:"Padat", config:"[Xe] 4f¹⁴ 5d³ 6s²", shells:[2,8,18,32,11,2],
    discovered:"Anders Ekeberg (1802)", desc:"Sangat tahan korosi, biokompatibel dengan tubuh manusia. Digunakan dalam kapasitor elektronik (60% tantalum digunakan untuk ini), implan tulang, dan peralatan kimia.",
    uses:["Kapasitor","Implan Tulang","Peralatan Kimia","Superalloy"] },
  { z:74, sym:"W", name:"Wolfram", mass:183.84, cat:"transition", group:6, period:6, block:"d",
    melt:3422, boil:5555, density:19.25, eneg:2.36, radius:193,
    phase:"Padat", config:"[Xe] 4f¹⁴ 5d⁴ 6s²", shells:[2,8,18,32,12,2],
    discovered:"José and Fausto Elhuyar (1783)", desc:"Memiliki titik leleh tertinggi dari semua unsur (3422°C). Digunakan dalam filamen lampu pijar. Karbida tungsten digunakan untuk alat pemotong yang sangat keras.",
    uses:["Filamen Lampu","Karbida Keras","Peluru","Elektroda Las"] },
  { z:75, sym:"Re", name:"Renium", mass:186.21, cat:"transition", group:7, period:6, block:"d",
    melt:3186, boil:5596, density:21.02, eneg:1.9, radius:188,
    phase:"Padat", config:"[Xe] 4f¹⁴ 5d⁵ 6s²", shells:[2,8,18,32,13,2],
    discovered:"Walter Noddack (1925)", desc:"Salah satu logam terlangka di bumi. Memiliki titik didih tertinggi setelah tungsten. Digunakan dalam superalloy untuk turbin jet dan dalam katalis reformasi bensin.",
    uses:["Turbin Jet","Katalis","Filamen","Superalloy"] },
  { z:76, sym:"Os", name:"Osmium", mass:190.23, cat:"transition", group:8, period:6, block:"d",
    melt:3033, boil:5012, density:22.59, eneg:2.2, radius:185,
    phase:"Padat", config:"[Xe] 4f¹⁴ 5d⁶ 6s²", shells:[2,8,18,32,14,2],
    discovered:"Smithson Tennant (1803)", desc:"Logam terdensitas alami yang diketahui (22.59 g/cm³). Osmium tetroksida sangat beracun. Digunakan dalam paduan logam keras untuk ujung pena dan kontak listrik.",
    uses:["Paduan Keras","Ujung Pena","Elektroda","Mikroskopi"] },
  { z:77, sym:"Ir", name:"Iridium", mass:192.22, cat:"transition", group:9, period:6, block:"d",
    melt:2446, boil:4428, density:22.56, eneg:2.2, radius:180,
    phase:"Padat", config:"[Xe] 4f¹⁴ 5d⁷ 6s²", shells:[2,8,18,32,15,2],
    discovered:"Smithson Tennant (1803)", desc:"Logam paling tahan korosi. Anomali iridium di lapisan K-Pg (Cretaceous-Paleogene) adalah bukti dampak asteroid yang memusnahkan dinosaurus 66 juta tahun lalu.",
    uses:["Standar Kilogram","Elektroda","Busi","Galvano"] },
  { z:78, sym:"Pt", name:"Platina", mass:195.08, cat:"transition", group:10, period:6, block:"d",
    melt:1768.3, boil:3825, density:21.45, eneg:2.28, radius:177,
    phase:"Padat", config:"[Xe] 4f¹⁴ 5d⁹ 6s¹", shells:[2,8,18,32,17,1],
    discovered:"Antonio de Ulloa (1735)", desc:"Logam mulia yang digunakan sebagai standar massa dan dalam katalis. Konverter katalitik menggunakan platinum untuk mengurangi polusi kendaraan. Sangat penting untuk sel bahan bakar hidrogen.",
    uses:["Perhiasan","Katalis","Sel Bahan Bakar","Standar"] },
  { z:79, sym:"Au", name:"Emas", mass:196.97, cat:"transition", group:11, period:6, block:"d",
    melt:1064.18, boil:2856, density:19.3, eneg:2.54, radius:174,
    phase:"Padat", config:"[Xe] 4f¹⁴ 5d¹⁰ 6s¹", shells:[2,8,18,32,18,1],
    discovered:"Zaman Prasejarah", desc:"Logam mulia yang tidak berkarat atau teroksidasi. Penghantaran listrik sangat baik. Digunakan dalam elektronik, kedokteran gigi, dan sebagai cadangan nilai ekonomi.",
    uses:["Perhiasan","Elektronik","Kedokteran Gigi","Investasi"] },
  { z:80, sym:"Hg", name:"Merkuri", mass:200.59, cat:"transition", group:12, period:6, block:"d",
    melt:-38.83, boil:356.73, density:13.534, eneg:2.0, radius:171,
    phase:"Cair", config:"[Xe] 4f¹⁴ 5d¹⁰ 6s²", shells:[2,8,18,32,18,2],
    discovered:"Zaman Prasejarah", desc:"Satu-satunya logam yang berwujud cair pada suhu kamar. Sangat beracun bagi sistem saraf. Digunakan dalam termometer, barometer, dan lampu fluoresen kompak.",
    uses:["Termometer","Barometer","Lampu Neon","Klorin"] },
  { z:81, sym:"Tl", name:"Talium", mass:204.38, cat:"post-trans", group:13, period:6, block:"p",
    melt:304, boil:1473, density:11.85, eneg:1.62, radius:156,
    phase:"Padat", config:"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹", shells:[2,8,18,32,18,3],
    discovered:"William Crookes (1861)", desc:"Logam sangat beracun yang pernah digunakan sebagai racun tikus dan racun pembunuh manusia. Talium-201 digunakan dalam pencitraan jantung nuklir diagnostik.",
    uses:["Diagnostik Jantung","Elektronik","Kaca Inframerah","Penelitian"] },
  { z:82, sym:"Pb", name:"Timbal", mass:207.2, cat:"post-trans", group:14, period:6, block:"p",
    melt:327.46, boil:1749, density:11.34, eneg:1.87, radius:154,
    phase:"Padat", config:"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²", shells:[2,8,18,32,18,4],
    discovered:"Zaman Prasejarah", desc:"Digunakan sejak Zaman Romawi (pipa air). Timbal tetraetil digunakan sebagai bahan bakar anti-knocking hingga dilarang karena toksisitasnya. Digunakan dalam baterai timbal-asam.",
    uses:["Baterai","Perisai Radiasi","Peluru","Solder"] },
  { z:83, sym:"Bi", name:"Bismut", mass:208.98, cat:"post-trans", group:15, period:6, block:"p",
    melt:271.3, boil:1564, density:9.79, eneg:2.02, radius:143,
    phase:"Padat", config:"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³", shells:[2,8,18,32,18,5],
    discovered:"Claude François Geoffroy (1753)", desc:"Logam paling tidak radioaktif (memiliki waktu paruh 10¹⁹ tahun). Menggantikan timbal yang beracun dalam banyak aplikasi. Kristal bismut memiliki warna pelangi yang indah akibat lapisan oksida.",
    uses:["Obat Maag","Pengganti Timbal","Kosmetik","Pigmen"] },
  { z:84, sym:"Po", name:"Polonium", mass:209, cat:"post-trans", group:16, period:6, block:"p",
    melt:254, boil:962, density:9.32, eneg:2.0, radius:135,
    phase:"Padat", config:"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴", shells:[2,8,18,32,18,6],
    discovered:"Marie Curie (1898)", desc:"Ditemukan oleh Marie Curie dan dinamai dari tanah airnya, Polandia. Sangat radioaktif dan beracun. Digunakan sebagai sumber alpha dalam perangkat anti-statis dan ionisasi udara.",
    uses:["Anti-statis","Sumber Alpha","Penelitian","Ionisasi"] },
  { z:85, sym:"At", name:"Astatin", mass:210, cat:"halogen", group:17, period:6, block:"p",
    melt:302, boil:337, density:7, eneg:2.2, radius:127,
    phase:"Padat", config:"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵", shells:[2,8,18,32,18,7],
    discovered:"Dale R. Corson (1940)", desc:"Unsur paling langka di kerak bumi, hanya ada sekitar 28 gram. Radioaktif dengan waktu paruh sangat pendek. At-211 menjanjikan untuk terapi radiasi target dalam pengobatan kanker.",
    uses:["Terapi Kanker","Penelitian Nuklir"] },
  { z:86, sym:"Rn", name:"Radon", mass:222, cat:"noble", group:18, period:6, block:"p",
    melt:-71, boil:-61.7, density:0.00973, eneg:null, radius:120,
    phase:"Gas", config:"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶", shells:[2,8,18,32,18,8],
    discovered:"Friedrich Ernst Dorn (1900)", desc:"Gas mulia radioaktif yang terbentuk dari peluruhan radium. Merupakan penyebab kanker paru-paru terbesar kedua setelah merokok. Dapat terakumulasi di ruang bawah tanah.",
    uses:["Terapi Kanker (historis)","Seismologi","Penelitian"] },
  // Period 7
  { z:87, sym:"Fr", name:"Fransium", mass:223, cat:"alkali", group:1, period:7, block:"s",
    melt:21, boil:650, density:1.87, eneg:0.7, radius:348,
    phase:"Padat", config:"[Rn] 7s¹", shells:[2,8,18,32,18,8,1],
    discovered:"Marguerite Perey (1939)", desc:"Logam alkali paling berat dan radioaktif. Hanya ada beberapa ratus atom fransium di kerak bumi pada waktu tertentu. Ditemukan oleh ilmuwan wanita Perancis Marguerite Perey.",
    uses:["Penelitian Ilmiah"] },
  { z:88, sym:"Ra", name:"Radium", mass:226, cat:"alkaline", group:2, period:7, block:"s",
    melt:696, boil:1737, density:5.5, eneg:0.9, radius:283,
    phase:"Padat", config:"[Rn] 7s²", shells:[2,8,18,32,18,8,2],
    discovered:"Marie & Pierre Curie (1898)", desc:"Ditemukan oleh pasangan ilmuwan Marie dan Pierre Curie. Pernah digunakan dalam cat pendar jam glow-in-the-dark menyebabkan banyak pekerja sakit. Sekarang hanya untuk terapi medis.",
    uses:["Penelitian","Terapi Kanker (historis)","Radioluminescen"] },
  // Actinides
  { z:89, sym:"Ac", name:"Aktinium", mass:227, cat:"actinide", group:3, period:7, block:"f",
    melt:1050, boil:3200, density:10.07, eneg:1.1, radius:260,
    phase:"Padat", config:"[Rn] 6d¹ 7s²", shells:[2,8,18,32,18,9,2],
    discovered:"André-Louis Debierne (1899)", desc:"Logam radioaktif yang memberikan nama pada seri aktinida. Bersinar biru dalam gelap karena ionisasi udara oleh radiasi. Sangat langka di alam.",
    uses:["Penelitian","Sumber Neutron","Terapi Kanker"] },
  { z:90, sym:"Th", name:"Torium", mass:232.04, cat:"actinide", group:3, period:7, block:"f",
    melt:1750, boil:4820, density:11.72, eneg:1.3, radius:237,
    phase:"Padat", config:"[Rn] 6d² 7s²", shells:[2,8,18,32,18,10,2],
    discovered:"Jöns Jacob Berzelius (1828)", desc:"Bahan bakar nuklir alternatif yang lebih melimpah dari uranium. Reaktor Molten Salt berbasis torium dianggap lebih aman. Digunakan dalam elektroda tungsten untuk pengelasan TIG.",
    uses:["Elektroda Las","Bahan Bakar Nuklir","Optik","Penelitian"] },
  { z:91, sym:"Pa", name:"Protaktinium", mass:231.04, cat:"actinide", group:3, period:7, block:"f",
    melt:1572, boil:4000, density:15.37, eneg:1.5, radius:243,
    phase:"Padat", config:"[Rn] 5f² 6d¹ 7s²", shells:[2,8,18,32,20,9,2],
    discovered:"Kasimir Fajans (1913)", desc:"Logam aktinida yang sangat radioaktif dan beracun. Sangat langka dan tidak memiliki kegunaan komersial. Terutama digunakan untuk penelitian ilmiah.",
    uses:["Penelitian Ilmiah"] },
  { z:92, sym:"U", name:"Uranium", mass:238.03, cat:"actinide", group:3, period:7, block:"f",
    melt:1135, boil:4131, density:19.05, eneg:1.38, radius:240,
    phase:"Padat", config:"[Rn] 5f³ 6d¹ 7s²", shells:[2,8,18,32,21,9,2],
    discovered:"Martin Heinrich Klaproth (1789)", desc:"Bahan bakar utama reaktor nuklir. Uranium-235 dapat mengalami fisi yang menghasilkan energi besar. Satu kilogram U-235 menghasilkan energi setara 3 juta kg batu bara.",
    uses:["Reaktor Nuklir","Senjata Nuklir","Kaca Uranium","Penetrator"] },
  { z:93, sym:"Np", name:"Neptunium", mass:237, cat:"actinide", group:3, period:7, block:"f",
    melt:644, boil:4000, density:20.25, eneg:1.36, radius:221,
    phase:"Padat", config:"[Rn] 5f⁴ 6d¹ 7s²", shells:[2,8,18,32,22,9,2],
    discovered:"Edwin McMillan (1940)", desc:"Unsur transuranik pertama yang ditemukan. Dinamai dari planet Neptunus. Diproduksi dalam reaktor nuklir. Neptunium-237 memiliki waktu paruh 2.1 juta tahun.",
    uses:["Detektor Neutron","Produksi Plutonium","Penelitian"] },
  { z:94, sym:"Pu", name:"Plutonium", mass:244, cat:"actinide", group:3, period:7, block:"f",
    melt:640, boil:3228, density:19.84, eneg:1.28, radius:243,
    phase:"Padat", config:"[Rn] 5f⁶ 7s²", shells:[2,8,18,32,24,8,2],
    discovered:"Glenn Seaborg (1940)", desc:"Bahan senjata nuklir dan bahan bakar pembangkit nuklir. Pu-238 digunakan dalam generator radioisotop termoelektrik (RTG) untuk misi luar angkasa seperti Cassini dan Voyager.",
    uses:["Senjata Nuklir","Bahan Bakar Reaktor","RTG Luar Angkasa"] },
  { z:95, sym:"Am", name:"Amerisium", mass:243, cat:"actinide", group:3, period:7, block:"f",
    melt:1176, boil:2607, density:13.69, eneg:1.3, radius:244,
    phase:"Padat", config:"[Rn] 5f⁷ 7s²", shells:[2,8,18,32,25,8,2],
    discovered:"Glenn Seaborg (1944)", desc:"Ditemukan dalam abu reaktor nuklir. Am-241 digunakan dalam detektor asap ionisasi yang ada di hampir setiap rumah. Memancarkan partikel alfa yang mengionisasi udara.",
    uses:["Detektor Asap","Sumber Gamma","Penelitian"] },
  { z:96, sym:"Cm", name:"Curium", mass:247, cat:"actinide", group:3, period:7, block:"f",
    melt:1345, boil:3110, density:13.51, eneg:1.3, radius:245,
    phase:"Padat", config:"[Rn] 5f⁷ 6d¹ 7s²", shells:[2,8,18,32,25,9,2],
    discovered:"Glenn Seaborg (1944)", desc:"Dinamai untuk menghormati Marie dan Pierre Curie. Digunakan dalam spektrometer alfa di wahana Mars Pathfinder untuk menganalisis komposisi batuan Mars.",
    uses:["Analisis Mars","RTG","Penelitian Nuklir"] },
  { z:97, sym:"Bk", name:"Berkelium", mass:247, cat:"actinide", group:3, period:7, block:"f",
    melt:986, boil:null, density:14.79, eneg:1.3, radius:244,
    phase:"Padat", config:"[Rn] 5f⁹ 7s²", shells:[2,8,18,32,27,8,2],
    discovered:"Glenn Seaborg (1949)", desc:"Dinamai dari kota Berkeley, California. Sangat langka dan tidak ada kegunaan komersial. Digunakan hanya untuk penelitian ilmiah dan sintesis unsur super-berat.",
    uses:["Penelitian Ilmiah","Sintesis Unsur Baru"] },
  { z:98, sym:"Cf", name:"Californium", mass:251, cat:"actinide", group:3, period:7, block:"f",
    melt:900, boil:null, density:15.1, eneg:1.3, radius:245,
    phase:"Padat", config:"[Rn] 5f¹⁰ 7s²", shells:[2,8,18,32,28,8,2],
    discovered:"Glenn Seaborg (1950)", desc:"Pemancar neutron yang sangat kuat. Digunakan untuk memulai reaktor nuklir baru dan dalam pendeteksian logam dan tambang. Cf-252 digunakan dalam terapi kanker serviks.",
    uses:["Reaktor Nuklir","Detektor Logam","Terapi Kanker","Geologi"] },
  { z:99, sym:"Es", name:"Einsteinium", mass:252, cat:"actinide", group:3, period:7, block:"f",
    melt:860, boil:996, density:8.84, eneg:1.3, radius:245,
    phase:"Padat", config:"[Rn] 5f¹¹ 7s²", shells:[2,8,18,32,29,8,2],
    discovered:"Albert Ghiorso (1952)", desc:"Ditemukan dalam abu uji bom hidrogen 'Ivy Mike' tahun 1952. Dinamai dari Albert Einstein. Hanya diproduksi dalam jumlah mikroskopis di reaktor nuklir.",
    uses:["Penelitian Ilmiah"] },
  { z:100, sym:"Fm", name:"Fermium", mass:257, cat:"actinide", group:3, period:7, block:"f",
    melt:1527, boil:null, density:null, eneg:1.3, radius:245,
    phase:"Padat", config:"[Rn] 5f¹² 7s²", shells:[2,8,18,32,30,8,2],
    discovered:"Albert Ghiorso (1952)", desc:"Juga ditemukan dalam abu uji nuklir Ivy Mike. Dinamai dari fisikawan Enrico Fermi. Tidak ada kegunaan praktis di luar penelitian ilmiah dasar.",
    uses:["Penelitian Ilmiah"] },
  { z:101, sym:"Md", name:"Mendelevium", mass:258, cat:"actinide", group:3, period:7, block:"f",
    melt:827, boil:null, density:null, eneg:1.3, radius:246,
    phase:"Padat", config:"[Rn] 5f¹³ 7s²", shells:[2,8,18,32,31,8,2],
    discovered:"Glenn Seaborg (1955)", desc:"Dinamai dari Dmitri Mendeleev, pencipta tabel periodik. Diproduksi dengan menembakkan partikel alfa ke einsteinium. Hanya beberapa atom yang pernah dibuat.",
    uses:["Penelitian Ilmiah"] },
  { z:102, sym:"No", name:"Nobelium", mass:259, cat:"actinide", group:3, period:7, block:"f",
    melt:827, boil:null, density:null, eneg:1.3, radius:246,
    phase:"Padat", config:"[Rn] 5f¹⁴ 7s²", shells:[2,8,18,32,32,8,2],
    discovered:"Albert Ghiorso (1958)", desc:"Dinamai dari Alfred Nobel. Penelitian penemuan ini sempat kontroversial. Masa hidup isotop paling stabil hanya 58 menit.",
    uses:["Penelitian Ilmiah"] },
  { z:103, sym:"Lr", name:"Lawrensium", mass:262, cat:"actinide", group:3, period:7, block:"d",
    melt:1627, boil:null, density:null, eneg:1.3, radius:246,
    phase:"Padat", config:"[Rn] 5f¹⁴ 7s² 7p¹", shells:[2,8,18,32,32,8,3],
    discovered:"Albert Ghiorso (1961)", desc:"Aktinida terakhir dan unsur terberat yang dapat dibuat dalam jumlah yang cukup untuk dipelajari sifat kimianya. Dinamai dari Ernest Lawrence, penemu siklotron.",
    uses:["Penelitian Ilmiah"] },
  // Period 7 d-block
  { z:104, sym:"Rf", name:"Rutherfordium", mass:265, cat:"transition", group:4, period:7, block:"d",
    melt:2100, boil:5500, density:23.2, eneg:null, radius:null,
    phase:"Padat", config:"[Rn] 5f¹⁴ 6d² 7s²", shells:[2,8,18,32,32,10,2],
    discovered:"JINR/LBNL (1964/1969)", desc:"Unsur super-berat pertama. Dinamai dari Ernest Rutherford. Waktu paruh isotop paling stabil (Rf-267) adalah 1.3 jam. Hanya diproduksi dalam jumlah sangat sedikit.",
    uses:["Penelitian Ilmiah"] },
  { z:105, sym:"Db", name:"Dubnium", mass:268, cat:"transition", group:5, period:7, block:"d",
    melt:null, boil:null, density:29.3, eneg:null, radius:null,
    phase:"Padat", config:"[Rn] 5f¹⁴ 6d³ 7s²", shells:[2,8,18,32,32,11,2],
    discovered:"JINR/LBNL (1968/1970)", desc:"Dinamai dari kota Dubna, Rusia. Penemuan ini diperdebatkan antara ilmuwan Soviet dan Amerika. Waktu paruh sekitar 1 hari untuk isotop paling stabil.",
    uses:["Penelitian Ilmiah"] },
  { z:106, sym:"Sg", name:"Seaborgium", mass:271, cat:"transition", group:6, period:7, block:"d",
    melt:null, boil:null, density:35.0, eneg:null, radius:null,
    phase:"Padat", config:"[Rn] 5f¹⁴ 6d⁴ 7s²", shells:[2,8,18,32,32,12,2],
    discovered:"Albert Ghiorso (1974)", desc:"Dinamai dari Glenn Seaborg, satu-satunya orang yang masih hidup saat unsur dinamai darinya. Berperilaku seperti molibdenum dan tungsten sesuai prediksi.",
    uses:["Penelitian Ilmiah"] },
  { z:107, sym:"Bh", name:"Bohrium", mass:270, cat:"transition", group:7, period:7, block:"d",
    melt:null, boil:null, density:37.1, eneg:null, radius:null,
    phase:"Padat", config:"[Rn] 5f¹⁴ 6d⁵ 7s²", shells:[2,8,18,32,32,13,2],
    discovered:"GSI Helmholtz Centre (1981)", desc:"Dinamai dari fisikawan Niels Bohr. Berperilaku sesuai prediksi berdasarkan posisinya di bawah renium. Isotop paling stabil memiliki waktu paruh 61 detik.",
    uses:["Penelitian Ilmiah"] },
  { z:108, sym:"Hs", name:"Hassium", mass:269, cat:"transition", group:8, period:7, block:"d",
    melt:null, boil:null, density:40.7, eneg:null, radius:null,
    phase:"Padat", config:"[Rn] 5f¹⁴ 6d⁶ 7s²", shells:[2,8,18,32,32,14,2],
    discovered:"GSI Helmholtz Centre (1984)", desc:"Dinamai dari negara bagian Hesse di Jerman. Berperilaku seperti osmium. Hanya beberapa atom yang pernah diproduksi. Isotop paling stabil memiliki waktu paruh ~10 detik.",
    uses:["Penelitian Ilmiah"] },
  { z:109, sym:"Mt", name:"Meitnerium", mass:278, cat:"unknown", group:9, period:7, block:"d",
    melt:null, boil:null, density:37.4, eneg:null, radius:null,
    phase:"Padat", config:"[Rn] 5f¹⁴ 6d⁷ 7s²", shells:[2,8,18,32,32,15,2],
    discovered:"GSI Helmholtz Centre (1982)", desc:"Dinamai untuk menghormati fisikawan wanita Lise Meitner yang berkontribusi pada penemuan fisi nuklir. Isotop paling stabil memiliki waktu paruh sekitar 7.6 detik.",
    uses:["Penelitian Ilmiah"] },
  { z:110, sym:"Ds", name:"Darmstadtium", mass:281, cat:"unknown", group:10, period:7, block:"d",
    melt:null, boil:null, density:34.8, eneg:null, radius:null,
    phase:"Padat", config:"[Rn] 5f¹⁴ 6d⁹ 7s¹", shells:[2,8,18,32,32,17,1],
    discovered:"GSI Helmholtz Centre (1994)", desc:"Dinamai dari kota Darmstadt, Jerman. Diperkirakan berperilaku seperti platina. Waktu paruh isotop paling stabil Ds-281 adalah 12.7 detik.",
    uses:["Penelitian Ilmiah"] },
  { z:111, sym:"Rg", name:"Roentgenium", mass:282, cat:"unknown", group:11, period:7, block:"d",
    melt:null, boil:null, density:28.7, eneg:null, radius:null,
    phase:"Padat", config:"[Rn] 5f¹⁴ 6d¹⁰ 7s¹", shells:[2,8,18,32,32,18,1],
    discovered:"GSI Helmholtz Centre (1994)", desc:"Dinamai dari Wilhelm Röntgen, penemu sinar-X. Diperkirakan berperilaku seperti emas. Isotop paling stabil memiliki waktu paruh 26 detik.",
    uses:["Penelitian Ilmiah"] },
  { z:112, sym:"Cn", name:"Kopernikium", mass:285, cat:"transition", group:12, period:7, block:"d",
    melt:null, boil:null, density:23.7, eneg:null, radius:null,
    phase:"Gas", config:"[Rn] 5f¹⁴ 6d¹⁰ 7s²", shells:[2,8,18,32,32,18,2],
    discovered:"GSI Helmholtz Centre (1996)", desc:"Dinamai dari Nicolaus Copernicus. Mungkin berwujud gas pada suhu kamar karena efek relativistik. Waktu paruh 28.7 detik.",
    uses:["Penelitian Ilmiah"] },
  { z:113, sym:"Nh", name:"Nihonium", mass:286, cat:"post-trans", group:13, period:7, block:"p",
    melt:null, boil:null, density:16.0, eneg:null, radius:null,
    phase:"Padat", config:"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹", shells:[2,8,18,32,32,18,3],
    discovered:"RIKEN (2004)", desc:"Unsur pertama yang ditemukan di Asia (Jepang). Nihon berarti 'Jepang' dalam bahasa Jepang. Pertama kali disintesis di RIKEN dengan menembakkan ion bismut dengan seng.",
    uses:["Penelitian Ilmiah"] },
  { z:114, sym:"Fl", name:"Flerovium", mass:289, cat:"post-trans", group:14, period:7, block:"p",
    melt:null, boil:null, density:14.0, eneg:null, radius:null,
    phase:"Gas", config:"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²", shells:[2,8,18,32,32,18,4],
    discovered:"JINR (1999)", desc:"Dinamai dari Laboratorium Flerov di Dubna. Diperkirakan menjadi gas mulia karena efek relativistik meskipun bukan gas mulia secara struktural. Waktu paruh 2.1 detik.",
    uses:["Penelitian Ilmiah"] },
  { z:115, sym:"Mc", name:"Moscovium", mass:290, cat:"post-trans", group:15, period:7, block:"p",
    melt:null, boil:null, density:13.5, eneg:null, radius:null,
    phase:"Padat", config:"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³", shells:[2,8,18,32,32,18,5],
    discovered:"JINR (2003)", desc:"Dinamai dari Oblast Moskow, Rusia. Termasuk dalam 'pulau kestabilan' yang diprediksi para ilmuwan nuklir. Waktu paruh 220 milidetik.",
    uses:["Penelitian Ilmiah"] },
  { z:116, sym:"Lv", name:"Livermorium", mass:293, cat:"post-trans", group:16, period:7, block:"p",
    melt:null, boil:null, density:12.9, eneg:null, radius:null,
    phase:"Padat", config:"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴", shells:[2,8,18,32,32,18,6],
    discovered:"JINR/LLNL (2000)", desc:"Dinamai dari Laboratorium Nasional Lawrence Livermore. Diperkirakan memiliki sifat seperti polonium. Waktu paruh 53 milidetik untuk isotop paling stabil.",
    uses:["Penelitian Ilmiah"] },
  { z:117, sym:"Ts", name:"Tennessin", mass:294, cat:"halogen", group:17, period:7, block:"p",
    melt:null, boil:null, density:7.2, eneg:null, radius:null,
    phase:"Padat", config:"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵", shells:[2,8,18,32,32,18,7],
    discovered:"JINR (2010)", desc:"Dinamai dari negara bagian Tennessee, AS. Unsur kedua terberat yang dikonfirmasi. Waktu paruh 51 milidetik. Kemungkinan berperilaku berbeda dari halogen lainnya.",
    uses:["Penelitian Ilmiah"] },
  { z:118, sym:"Og", name:"Oganesson", mass:294, cat:"noble", group:18, period:7, block:"p",
    melt:null, boil:null, density:4.95, eneg:null, radius:null,
    phase:"Padat", config:"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶", shells:[2,8,18,32,32,18,8],
    discovered:"JINR/LLNL (2002)", desc:"Unsur terberat yang ditemukan dan dikonfirmasi. Dinamai dari fisikawan Yuri Oganessian. Diperkirakan berperilaku sebagai metaloid padat, bukan gas mulia seperti yang diharapkan.",
    uses:["Penelitian Ilmiah"] },
];

// Category metadata
const CATEGORIES = {
  "alkali":     { label: "Logam Alkali",       color: "#ff4d6d" },
  "alkaline":   { label: "Logam Alkali Tanah", color: "#ff8c42" },
  "transition": { label: "Logam Transisi",     color: "#4ecdc4" },
  "post-trans": { label: "Logam Pasca-Trans",  color: "#a8dadc" },
  "metalloid":  { label: "Metaloid",           color: "#ffd166" },
  "nonmetal":   { label: "Nonlogam",           color: "#06d6a0" },
  "halogen":    { label: "Halogen",            color: "#9d4edd" },
  "noble":      { label: "Gas Mulia",          color: "#4895ef" },
  "lanthanide": { label: "Lantanida",          color: "#f72585" },
  "actinide":   { label: "Aktinida",           color: "#b5179e" },
  "unknown":    { label: "Tidak Diketahui",    color: "#888" },
};
